/**
 * Core data model for the YIL marketplace.
 *
 * Tables:
 *   users                    — buyers and sellers (auth fields are owned by
 *                              YIL-4; we only carry the public profile here).
 *   auth_sessions            — server-side session store, indexed by JWT hash
 *                              (YIL-4).
 *   magic_link_tokens        — single-use tokens for passwordless auth and
 *                              email verification (YIL-4).
 *   categories               — flat taxonomy, slug-addressable, parent_id is
 *                              optional so we can build a tree later without a
 *                              migration.
 *   listings                 — items offered for sale by a seller.
 *   images                   — photos attached to a single listing, ordered.
 *   listing_categories       — many-to-many join between listings and
 *                              categories.
 *   orders                   — buyer–seller transactions on a listing (YIL-14).
 *   order_state_transitions  — append-only audit log of every status change
 *                              (YIL-14). One row per transition, with
 *                              actor identity, role, reason, and arbitrary
 *                              metadata (Stripe intent ids, tracking numbers,
 *                              dispute reasons, etc.).
 *   reviews                  — two-sided reviews on completed orders (YIL-10).
 *   review_flags             — user-driven abuse reports on reviews (YIL-10).
 *   review_moderation_actions — moderator decision audit trail (YIL-10).
 *
 * Conventions:
 *   - Primary keys are UUIDv4 generated by Postgres (`gen_random_uuid()`),
 *     not application-assigned. Keeps the API client-agnostic and avoids
 *     sequential-id enumeration leaks.
 *   - Every table has `created_at` / `updated_at`. `updated_at` is bumped by a
 *     trigger on UPDATE (see migration 0000).
 *   - User-generated content (`users`, `listings`, `images`, `orders`) is
 *     soft-deleted with `deleted_at`; `categories`,
 *     `order_state_transitions`, and `review_moderation_actions` are
 *     append-only history rows.
 *   - All FKs use `ON DELETE RESTRICT` to surface dangling-reference bugs as
 *     errors rather than silently losing history. Cascades are explicit on
 *     `images.listing_id` and `reviews.order_id` because a deleted listing
 *     should not retain orphan image rows, and reviews only exist on
 *     orders.
 *   - Money is stored as `amount_cents bigint` + `currency char(3)`. Never
 *     use floats for prices.
 *   - All timestamps are `timestamptz` in UTC.
 *
 * Order state machine (YIL-14):
 *   See docs/architecture/transactions.md and
 *   docs/adr/0003-order-state-machine.md. The `order_state` enum is the
 *   single source of truth for legal states; the
 *   `orders_status_transition_allowed` CHECK constraint on
 *   `order_state_transitions` enforces legal (from_state, to_state) pairs in
 *   the database, and `src/orders/state-machine.ts` enforces both legal
 *   transitions and actor-role permissions in application code with
 *   structured guard failures.
 */
import {
  pgTable,
  pgEnum,
  uuid,
  text,
  varchar,
  bigint,
  integer,
  boolean,
  timestamp,
  primaryKey,
  index,
  uniqueIndex,
  check,
  customType,
  jsonb,
} from "drizzle-orm/pg-core";
import { sql, relations } from "drizzle-orm";

/* -------------------------------------------------------------------------- */
/*  Custom types                                                              */
/* -------------------------------------------------------------------------- */

// YIL-8 — Postgres `tsvector`. Drizzle's pg-core doesn't ship a built-in
// type for it, so we declare it as an opaque custom type. We never insert
// into it (it's generated) so `dataType()` only matters for the DDL emit.
const tsvector = customType<{ data: string; driverData: string }>({
  dataType() {
    return "tsvector";
  },
});

/* -------------------------------------------------------------------------- */
/*  Enums                                                                     */
/* -------------------------------------------------------------------------- */

export const userRole = pgEnum("user_role", ["buyer", "seller", "admin"]);

export const listingStatus = pgEnum("listing_status", [
  "draft",
  "published",
  "sold",
  "archived",
]);

/* -------------------------------------------------------------------------- */
/*  users                                                                     */
/* -------------------------------------------------------------------------- */

export const users = pgTable(
  "users",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    // Public handle / display name.
    handle: varchar("handle", { length: 32 }).notNull(),
    displayName: varchar("display_name", { length: 80 }).notNull(),
    bio: text("bio").notNull().default(""),
    avatarUrl: text("avatar_url"),
    role: userRole("role").notNull().default("buyer"),
    /* -------------------------------------------------------------------- */
    /*  YIL-4 — Auth fields                                                 */
    /* -------------------------------------------------------------------- */
    // email is the canonical auth subject. Stored lowercased so the unique
    // index is case-insensitive at the application layer.
    email: varchar("email", { length: 254 }).notNull(),
    // bcrypt hash. NULL when the account was created via magic-link only
    // and the user has never set a password.
    passwordHash: text("password_hash"),
    emailVerified: boolean("email_verified").notNull().default(false),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
  },
  (t) => ({
    handleUnique: uniqueIndex("users_handle_unique").on(t.handle),
    emailUnique: uniqueIndex("users_email_unique").on(t.email),
    activeUsersIdx: index("users_active_idx")
      .on(t.createdAt)
      .where(sql`${t.deletedAt} IS NULL`),
  })
);

/* -------------------------------------------------------------------------- */
/*  YIL-4 — Auth                                                              */
/* -------------------------------------------------------------------------- */

/**
 * Server-side session records. The cookie carries a signed JWT whose payload
 * is `{ sid, sub, exp }`. The DB row is the source of truth: we can revoke
 * immediately on logout / password change / suspicious activity without
 * waiting for the JWT to expire. `token_hash` is sha-256 of the *JWT string*
 * so we can look up by cookie value without an extra index leak.
 */
export const authSessions = pgTable(
  "auth_sessions",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    tokenHash: text("token_hash").notNull(),
    userAgent: text("user_agent"),
    ipHash: text("ip_hash"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    lastSeenAt: timestamp("last_seen_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    revokedAt: timestamp("revoked_at", { withTimezone: true }),
  },
  (t) => ({
    tokenHashUnique: uniqueIndex("auth_sessions_token_hash_unique").on(
      t.tokenHash
    ),
    userIdx: index("auth_sessions_user_idx").on(t.userId),
  })
);

/**
 * Single-use magic-link tokens, sent by email. Used for two flows:
 *   1. Passwordless sign-in / sign-up.
 *   2. Email verification (after a password sign-up we can mail a link).
 * `token_hash` is sha-256 of the random token we mailed — never store the
 * raw token so a DB leak does not enable account takeover.
 */
export const magicLinkTokens = pgTable(
  "magic_link_tokens",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    email: varchar("email", { length: 254 }).notNull(),
    tokenHash: text("token_hash").notNull(),
    // 'signin' | 'verify_email'
    purpose: varchar("purpose", { length: 32 }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    consumedAt: timestamp("consumed_at", { withTimezone: true }),
  },
  (t) => ({
    tokenHashUnique: uniqueIndex("magic_link_tokens_token_hash_unique").on(
      t.tokenHash
    ),
    emailIdx: index("magic_link_tokens_email_idx").on(t.email),
  })
);

/* -------------------------------------------------------------------------- */
/*  categories                                                                */
/* -------------------------------------------------------------------------- */

export const categories = pgTable(
  "categories",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    // Slug is the URL-addressable identifier; human label lives in `name`.
    slug: varchar("slug", { length: 64 }).notNull(),
    name: varchar("name", { length: 80 }).notNull(),
    description: text("description").notNull().default(""),
    // Optional parent for future tree structure; null = top-level.
    parentId: uuid("parent_id"),
    position: integer("position").notNull().default(0),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    slugUnique: uniqueIndex("categories_slug_unique").on(t.slug),
    parentIdx: index("categories_parent_idx").on(t.parentId),
  })
);

/* -------------------------------------------------------------------------- */
/*  listings                                                                  */
/* -------------------------------------------------------------------------- */

export const listings = pgTable(
  "listings",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    sellerId: uuid("seller_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),
    title: varchar("title", { length: 140 }).notNull(),
    description: text("description").notNull().default(""),
    // Money — see header comment. Keep currency explicit so we can ship
    // multi-currency later without a destructive migration.
    amountCents: bigint("amount_cents", { mode: "number" }).notNull(),
    currency: varchar("currency", { length: 3 }).notNull().default("USD"),
    status: listingStatus("status").notNull().default("draft"),
    // Free-form inventory location; structured fields ship in a later issue.
    location: varchar("location", { length: 120 }).notNull().default(""),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
    // YIL-8 — Postgres full-text search vector. Generated from title (weight A)
    // and description (weight B). Maintained by Postgres; the app never writes
    // to it. Indexes are declared in the table builder below.
    searchVector: tsvector("search_vector"),
  },
  (t) => ({
    sellerIdx: index("listings_seller_idx").on(t.sellerId),
    // Hot browse path: live listings newest-first.
    activeByCreatedIdx: index("listings_active_by_created_idx")
      .on(t.createdAt.desc())
      .where(sql`${t.deletedAt} IS NULL`),
    activeByStatusIdx: index("listings_active_by_status_idx")
      .on(t.status, t.createdAt.desc())
      .where(sql`${t.deletedAt} IS NULL`),
    priceNonNegative: check(
      "listings_amount_cents_non_negative",
      sql`${t.amountCents} >= 0`
    ),
    // YIL-8 — GIN over the generated search_vector for FTS lookups.
    searchVectorGinIdx: index("listings_search_vector_gin_idx").using(
      "gin",
      t.searchVector
    ),
    // YIL-8 — trigram GIN on lower(title) for typo-tolerant prefix matching.
    titleTrgmGinIdx: index("listings_title_trgm_gin_idx").using(
      "gin",
      sql`lower(${t.title}) gin_trgm_ops`
    ),
  })
);

/* -------------------------------------------------------------------------- */
/*  images                                                                    */
/* -------------------------------------------------------------------------- */

export const images = pgTable(
  "images",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    listingId: uuid("listing_id")
      .notNull()
      .references(() => listings.id, { onDelete: "cascade" }),
    // `key` is the object-storage key (S3/R2/etc). We store the full URL too
    // so reads don't need a join; `key` is for write paths that rotate CDN.
    storageKey: varchar("storage_key", { length: 256 }).notNull(),
    url: text("url").notNull(),
    altText: varchar("alt_text", { length: 200 }).notNull().default(""),
    width: integer("width"),
    height: integer("height"),
    position: integer("position").notNull().default(0),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
  },
  (t) => ({
    listingIdx: index("images_listing_idx").on(t.listingId),
    listingPositionIdx: index("images_listing_position_idx").on(
      t.listingId,
      t.position
    ),
    storageKeyUnique: uniqueIndex("images_storage_key_unique").on(t.storageKey),
  })
);

/* -------------------------------------------------------------------------- */
/*  listing_categories (M:N)                                                  */
/* -------------------------------------------------------------------------- */

export const listingCategories = pgTable(
  "listing_categories",
  {
    listingId: uuid("listing_id")
      .notNull()
      .references(() => listings.id, { onDelete: "cascade" }),
    categoryId: uuid("category_id")
      .notNull()
      .references(() => categories.id, { onDelete: "restrict" }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    pk: primaryKey({ columns: [t.listingId, t.categoryId] }),
    categoryIdx: index("listing_categories_category_idx").on(t.categoryId),
  })
);

/* -------------------------------------------------------------------------- */
/*  Relations (for Drizzle's relational query API)                            */
/* -------------------------------------------------------------------------- */

export const usersRelations = relations(users, ({ many }) => ({
  listings: many(listings),
}));

export const categoriesRelations = relations(categories, ({ many, one }) => ({
  parent: one(categories, {
    fields: [categories.parentId],
    references: [categories.id],
    relationName: "category_parent",
  }),
  listings: many(listingCategories),
}));

export const listingsRelations = relations(listings, ({ one, many }) => ({
  seller: one(users, {
    fields: [listings.sellerId],
    references: [users.id],
  }),
  images: many(images),
  categories: many(listingCategories),
}));

export const imagesRelations = relations(images, ({ one }) => ({
  listing: one(listings, {
    fields: [images.listingId],
    references: [listings.id],
  }),
}));

export const listingCategoriesRelations = relations(
  listingCategories,
  ({ one }) => ({
    listing: one(listings, {
      fields: [listingCategories.listingId],
      references: [listings.id],
    }),
    category: one(categories, {
      fields: [listingCategories.categoryId],
      references: [categories.id],
    }),
  })
);

/* -------------------------------------------------------------------------- */
/*  Inferred types — import these from app code, never re-derive.             */
/* -------------------------------------------------------------------------- */

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;

export type Category = typeof categories.$inferSelect;
export type NewCategory = typeof categories.$inferInsert;

export type Listing = typeof listings.$inferSelect;
export type NewListing = typeof listings.$inferInsert;

export type Image = typeof images.$inferSelect;
export type NewImage = typeof images.$inferInsert;

export type ListingCategory = typeof listingCategories.$inferSelect;
export type NewListingCategory = typeof listingCategories.$inferInsert;

export type AuthSession = typeof authSessions.$inferSelect;
export type NewAuthSession = typeof authSessions.$inferInsert;

export type MagicLinkToken = typeof magicLinkTokens.$inferSelect;
export type NewMagicLinkToken = typeof magicLinkTokens.$inferInsert;

/* -------------------------------------------------------------------------- */
/*  YIL-10 — Reviews and ratings                                              */
/* -------------------------------------------------------------------------- */

/**
 * Orders drive the review lifecycle. A review can only be written once the
 * order has reached the `completed` state. Earlier states (initiated, paid,
 * fulfilled) intentionally disallow reviews so neither side can weaponize
 * them against the other before the deal is done. `disputed` also blocks
 * reviews; resolution is its own flow.
 *
 * State machine (canonical source: src/orders/state-machine.ts):
 *
 *   initiated ──► paid ──► fulfilled ──► completed
 *       │           │           │             │
 *       ▼           ▼           ▼             ▼
 *   cancelled   cancelled   disputed      disputed
 *                               │
 *                               ▼
 *                         completed | cancelled   (admin resolution)
 *
 * Every state transition is recorded in `order_state_transitions`. The DB
 * enforces legal (from_state, to_state) pairs via a CHECK constraint; the
 * app enforces which actor role may perform which transition. See ADR
 * 0002 for the rationale on splitting these two layers.
 */
export const orderState = pgEnum("order_state", [
  "initiated",
  "paid",
  "fulfilled",
  "completed",
  "disputed",
  "cancelled",
]);

/**
 * Who is recorded as having caused a transition. `system` covers automated
 * paths (Stripe webhooks, auto-confirm timers, settlement jobs); the actor
 * foreign key is nullable in that case. Buyers and sellers are the order's
 * own parties; admin covers operator actions from the admin console.
 */
export const orderTransitionActor = pgEnum("order_transition_actor", [
  "buyer",
  "seller",
  "admin",
  "system",
]);

export const orders = pgTable(
  "orders",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    listingId: uuid("listing_id")
      .notNull()
      .references(() => listings.id, { onDelete: "restrict" }),
    buyerId: uuid("buyer_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),
    sellerId: uuid("seller_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),
    state: orderState("state").notNull().default("initiated"),
    /**
     * Captured at order creation so later listing price changes don't
     * retroactively rewrite history. Kept in minor units (e.g. cents).
     */
    amountMinor: bigint("amount_minor", { mode: "number" }).notNull(),
    currency: varchar("currency", { length: 3 }).notNull().default("USD"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    // YIL-14 — state-specific audit timestamps. These mirror the *first* time
    // the order entered the named state and are denormalized on the orders
    // row so common operational queries ("average time to fulfilment")
    // don't have to walk the audit table. The audit table remains the
    // authoritative source for *who* and *why*.
    paidAt: timestamp("paid_at", { withTimezone: true }),
    fulfilledAt: timestamp("fulfilled_at", { withTimezone: true }),
    disputedAt: timestamp("disputed_at", { withTimezone: true }),
    cancelledAt: timestamp("cancelled_at", { withTimezone: true }),
  },
  (t) => ({
    sellerIdx: index("orders_seller_idx").on(t.sellerId, t.createdAt),
    buyerIdx: index("orders_buyer_idx").on(t.buyerId, t.createdAt),
    stateIdx: index("orders_state_idx").on(t.state, t.createdAt),
    /**
     * One active (non-cancelled) order per (buyer, listing) at a time.
     * Buyers can retry after cancelling — `cancelled` is excluded from
     * the partial unique index below.
     */
    activeByBuyer: uniqueIndex("orders_active_buyer_unique")
      .on(t.buyerId, t.listingId)
      .where(sql`${t.state} <> 'cancelled'`),
    amountNonNegative: check(
      "orders_amount_minor_non_negative",
      sql`${t.amountMinor} >= 0`
    ),
    /**
     * State-timestamp consistency: if the order is in the named state, the
     * matching timestamp must be set. The reverse (timestamp set but state
     * not yet advanced) is allowed so the trigger in migration 0003 can
     * update the timestamp before the state column in a single UPDATE.
     */
    paidConsistency: check(
      "orders_paid_at_consistency",
      sql`(${t.state} IN ('paid','fulfilled','completed','disputed'))
          OR ${t.paidAt} IS NULL`
    ),
    fulfilledConsistency: check(
      "orders_fulfilled_at_consistency",
      sql`(${t.state} IN ('fulfilled','completed','disputed'))
          OR ${t.fulfilledAt} IS NULL`
    ),
    completedConsistency: check(
      "orders_completed_at_consistency",
      sql`(${t.state} = 'completed')
          OR ${t.completedAt} IS NULL`
    ),
    disputedConsistency: check(
      "orders_disputed_at_consistency",
      sql`(${t.state} = 'disputed')
          OR ${t.disputedAt} IS NULL`
    ),
    cancelledConsistency: check(
      "orders_cancelled_at_consistency",
      sql`(${t.state} = 'cancelled')
          OR ${t.cancelledAt} IS NULL`
    ),
  })
);

/**
 * YIL-14 — Append-only audit log of every state transition on an order.
 *
 * One row is written for each successful transition. The application
 * computes `from_state` and `to_state`, then INSERTs. A CHECK constraint
 * rejects any (from_state, to_state) pair that is not in the allowed set,
 * which gives us a defense-in-depth guarantee even if the application layer
 * is bypassed (e.g. by a raw SQL maintenance script).
 *
 * `actor_user_id` is nullable because `system` transitions (Stripe webhook
 * marking an order paid, auto-confirm timer marking an order completed)
 * have no human actor. `actor_role` is always present and tells you what
 * *kind* of actor was responsible.
 *
 * `metadata` is intentionally jsonb and opaque to the schema: each
 * transition can carry whatever context it needs (Stripe PaymentIntent id,
 * tracking number, dispute evidence url, admin note). The application
 * documents the expected shape per transition in src/orders/state-machine.ts.
 *
 * No updated_at — audit rows are immutable. No deleted_at — we never
 * erase history. If a row was inserted in error, write a counter-row.
 */
export const orderStateTransitions = pgTable(
  "order_state_transitions",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    orderId: uuid("order_id")
      .notNull()
      .references(() => orders.id, { onDelete: "restrict" }),
    // null on the very first row for an order (the order row itself is
    // created in 'initiated' state; no transition row precedes it).
    fromState: orderState("from_state"),
    toState: orderState("to_state").notNull(),
    actorUserId: uuid("actor_user_id").references(() => users.id, {
      onDelete: "restrict",
    }),
    actorRole: orderTransitionActor("actor_role").notNull(),
    // Free-form, human-readable. Truncated to 500 chars at the DB layer to
    // keep the audit table light; longer narratives go in `metadata`.
    reason: varchar("reason", { length: 500 }).notNull().default(""),
    // Transition-specific structured context. Examples:
    //   paid       → { stripe_payment_intent_id, stripe_charge_id }
    //   fulfilled  → { carrier, tracking_number }
    //   disputed   → { opened_by, evidence_url }
    //   completed  → { via: "buyer_confirm" | "auto_confirm" | "admin_resolve" }
    metadata: jsonb("metadata").notNull().default(sql`'{}'::jsonb`),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    /**
     * Hot read path: "show me the history of order X". Sort by created_at
     * so the natural ordering of the audit log matches insertion order.
     */
    orderHistoryIdx: index("order_state_transitions_order_history_idx").on(
      t.orderId,
      t.createdAt
    ),
    /**
     * Operational: "show me everything buyer U did to orders".
     */
    actorIdx: index("order_state_transitions_actor_idx").on(
      t.actorUserId,
      t.createdAt
    ),
    /**
     * Operational: "show me all open disputes opened in the last 24h".
     */
    toStateIdx: index("order_state_transitions_to_state_idx").on(
      t.toState,
      t.createdAt
    ),
    /**
     * Defense-in-depth: the (from_state, to_state) pair must be a legal
     * transition. The canonical allow-list lives in
     * src/orders/state-machine.ts and is mirrored here so the database
     * itself can reject illegal rows.
     */
    legalTransition: check(
      "orders_status_transition_allowed",
      sql`(${t.fromState}, ${t.toState}) IN (
        ('initiated',  'paid'),
        ('initiated',  'cancelled'),
        ('paid',       'fulfilled'),
        ('paid',       'disputed'),
        ('paid',       'cancelled'),
        ('fulfilled',  'completed'),
        ('fulfilled',  'disputed'),
        ('completed',  'disputed'),
        ('disputed',   'completed'),
        ('disputed',   'cancelled')
      )`
    ),
    /**
     * Actor consistency: `system` is the only role that may have a NULL
     * actor_user_id. Every buyer/seller/admin row must point at a real
     * user. (The FK enforces existence when present.)
     */
    actorRoleConsistency: check(
      "orders_transition_actor_consistency",
      sql`(${t.actorRole} = 'system') = (${t.actorUserId} IS NULL)`
    ),
  })
);

/**
 * Who is writing the review, from the order's POV.
 *  - `buyer`  = the buyer writing about the seller
 *  - `seller` = the seller writing about the buyer
 *
 * Two-sided means exactly one of each per completed order, written by the
 * party themselves. We never let one side impersonate the other, and we
 * never auto-fill a review.
 */
export const reviewRole = pgEnum("review_role", ["buyer", "seller"]);

export const reviews = pgTable(
  "reviews",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    orderId: uuid("order_id")
      .notNull()
      .references(() => orders.id, { onDelete: "cascade" }),
    reviewerId: uuid("reviewer_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),
    revieweeId: uuid("reviewee_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),
    role: reviewRole("role").notNull(),
    /** 1..5 inclusive. Enforced by a check constraint below. */
    rating: integer("rating").notNull(),
    body: text("body").notNull().default(""),
    /** Soft-hide when a moderator removes the review for abuse. */
    hiddenAt: timestamp("hidden_at", { withTimezone: true }),
    hiddenReason: text("hidden_reason"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    /**
     * One review per (order, role). The buyer writes one review for the
     * seller, and the seller writes one review for the buyer.
     */
    onePerSide: uniqueIndex("reviews_one_per_side_unique").on(t.orderId, t.role),
    revieweeIdx: index("reviews_reviewee_idx").on(t.revieweeId, t.createdAt),
    reviewerIdx: index("reviews_reviewer_idx").on(t.reviewerId, t.createdAt),
    orderIdx: index("reviews_order_idx").on(t.orderId),
    /** DB-level guard: ratings must be 1..5. */
    ratingRange: check(
      "reviews_rating_range",
      sql`${t.rating} between 1 and 5`
    ),
  })
);

/**
 * User-driven abuse reports. Multiple users can flag the same review; the
 * system counts flags and escalates once a threshold is hit. Moderators act
 * via the separate `review_moderation_actions` audit table — we keep
 * *reports* and *decisions* in distinct tables so the audit trail is honest.
 */
export const reviewFlagReason = pgEnum("review_flag_reason", [
  "spam",
  "harassment",
  "hate",
  "threat",
  "doxxing",
  "off_topic",
  "other",
]);

export const reviewFlags = pgTable(
  "review_flags",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    reviewId: uuid("review_id")
      .notNull()
      .references(() => reviews.id, { onDelete: "cascade" }),
    reporterId: uuid("reporter_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),
    reason: reviewFlagReason("reason").notNull(),
    notes: text("notes").notNull().default(""),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    resolvedAt: timestamp("resolved_at", { withTimezone: true }),
    resolution: text("resolution"),
  },
  (t) => ({
    /** One reporter can flag the same review once; duplicates are merged. */
    onePerReporter: uniqueIndex("review_flags_one_per_reporter").on(
      t.reviewId,
      t.reporterId
    ),
    /** Common read path: all open flags on a given review. */
    openByReview: index("review_flags_open_by_review_idx")
      .on(t.reviewId)
      .where(sql`${t.resolvedAt} IS NULL`),
  })
);

/**
 * Append-only audit of moderator decisions on flagged reviews. The admin
 * console reads this for "why was this review removed". The flag table holds
 * the *reports*; this table holds the *decisions*.
 */
export const reviewModerationActions = pgTable(
  "review_moderation_actions",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    reviewId: uuid("review_id")
      .notNull()
      .references(() => reviews.id, { onDelete: "cascade" }),
    actorId: uuid("actor_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),
    action: text("action").notNull(),
    reason: text("reason").notNull().default(""),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    reviewIdx: index("review_moderation_actions_review_idx").on(
      t.reviewId,
      t.createdAt
    ),
  })
);

export type Order = typeof orders.$inferSelect;
export type NewOrder = typeof orders.$inferInsert;

export type OrderStateTransition = typeof orderStateTransitions.$inferSelect;
export type NewOrderStateTransition =
  typeof orderStateTransitions.$inferInsert;

export type Review = typeof reviews.$inferSelect;
export type NewReview = typeof reviews.$inferInsert;

export type ReviewFlag = typeof reviewFlags.$inferSelect;
export type NewReviewFlag = typeof reviewFlags.$inferInsert;

export type ReviewModerationAction =
  typeof reviewModerationActions.$inferSelect;
export type NewReviewModerationAction =
  typeof reviewModerationActions.$inferInsert;

/* -------------------------------------------------------------------------- */
/*  Relations — reviews                                                        */
/* -------------------------------------------------------------------------- */

export const ordersRelations = relations(orders, ({ one, many }) => ({
  listing: one(listings, {
    fields: [orders.listingId],
    references: [listings.id],
  }),
  buyer: one(users, {
    fields: [orders.buyerId],
    references: [users.id],
    relationName: "order_buyer",
  }),
  seller: one(users, {
    fields: [orders.sellerId],
    references: [users.id],
    relationName: "order_seller",
  }),
  reviews: many(reviews),
  transitions: many(orderStateTransitions),
}));

export const orderStateTransitionsRelations = relations(
  orderStateTransitions,
  ({ one }) => ({
    order: one(orders, {
      fields: [orderStateTransitions.orderId],
      references: [orders.id],
    }),
    actor: one(users, {
      fields: [orderStateTransitions.actorUserId],
      references: [users.id],
    }),
  })
);

export const reviewsRelations = relations(reviews, ({ one, many }) => ({
  order: one(orders, {
    fields: [reviews.orderId],
    references: [orders.id],
  }),
  reviewer: one(users, {
    fields: [reviews.reviewerId],
    references: [users.id],
    relationName: "review_reviewer",
  }),
  reviewee: one(users, {
    fields: [reviews.revieweeId],
    references: [users.id],
    relationName: "review_reviewee",
  }),
  flags: many(reviewFlags),
  moderationActions: many(reviewModerationActions),
}));

export const reviewFlagsRelations = relations(reviewFlags, ({ one }) => ({
  review: one(reviews, {
    fields: [reviewFlags.reviewId],
    references: [reviews.id],
  }),
  reporter: one(users, {
    fields: [reviewFlags.reporterId],
    references: [users.id],
  }),
}));

/* -------------------------------------------------------------------------- */
/*  YIL-9 — Stripe payments                                                   */
/* -------------------------------------------------------------------------- */

/**
 * Local shadow of a Stripe PaymentIntent.
 *
 * One row per Stripe PI. The `stripe_payment_intent_id` (pi_…) is the join
 * key the webhook handler uses to look us up. We never store card details;
 * Stripe is PCI-DSS Level 1 and we let them hold the PAN.
 *
 * State transitions are enforced by `src/payments/state.ts`; the DB also
 * has CHECK constraints + the payment_intents_refund_not_exceed invariant
 * as a last line of defense.
 *
 * Money columns are `bigint` minor units (cents for USD).
 */
export const paymentIntentState = pgEnum("payment_intent_state", [
  "pending",
  "authorized",
  "captured",
  "failed",
  "canceled",
  "refunded",
  "partially_refunded",
  "disputed",
]);

export const paymentIntents = pgTable(
  "payment_intents",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    orderId: uuid("order_id")
      .notNull()
      .references(() => orders.id, { onDelete: "restrict" }),
    stripePaymentIntentId: text("stripe_payment_intent_id").unique(),
    amountCents: bigint("amount_cents", { mode: "number" }).notNull(),
    currency: varchar("currency", { length: 3 }).notNull(),
    state: paymentIntentState("state").notNull().default("pending"),
    refundedAmountCents: bigint("refunded_amount_cents", { mode: "number" })
      .notNull()
      .default(0),
    lastErrorMessage: text("last_error_message"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    orderIdx: index("payment_intents_order_idx").on(t.orderId, t.createdAt),
    stateIdx: index("payment_intents_state_idx").on(t.state, t.createdAt),
    amountPositive: check(
      "payment_intents_amount_positive",
      sql`${t.amountCents} > 0`
    ),
    refundBounds: check(
      "payment_intents_refund_not_exceed",
      sql`${t.refundedAmountCents} <= ${t.amountCents}`
    ),
  })
);

/**
 * One row per Stripe Refund. Append-only — we never delete or update
 * after the row is written. Audit trail for refunds is part of the
 * account ledger (out of scope for this issue).
 */
export const refundKind = pgEnum("refund_kind", ["full", "partial"]);

export const refundReason = pgEnum("refund_reason", [
  "duplicate",
  "fraudulent",
  "requested_by_customer",
]);

export const refunds = pgTable(
  "refunds",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    paymentIntentId: uuid("payment_intent_id")
      .notNull()
      .references(() => paymentIntents.id, { onDelete: "cascade" }),
    stripeRefundId: text("stripe_refund_id").unique().notNull(),
    amountCents: bigint("amount_cents", { mode: "number" }).notNull(),
    kind: refundKind("kind").notNull(),
    reason: refundReason("reason"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    paymentIntentIdx: index("refunds_payment_intent_idx").on(
      t.paymentIntentId,
      t.createdAt
    ),
    amountPositive: check(
      "refunds_amount_positive",
      sql`${t.amountCents} > 0`
    ),
  })
);

/**
 * Dedupe table for inbound Stripe webhook events. We record every event
 * `id` (evt_…) we accept so replays become no-ops. Window: 24h (matches
 * Stripe's replay window for the same API call); see
 * `STRIPE_EVENT_DEDUPE_WINDOW_MS` in `payments/idempotency.ts`.
 */
export const stripeEventsSeen = pgTable(
  "stripe_events_seen",
  {
    eventId: text("event_id").primaryKey(),
    receivedAt: timestamp("received_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    receivedAtIdx: index("stripe_events_seen_received_at_idx").on(t.receivedAt),
  })
);

export type PaymentIntent = typeof paymentIntents.$inferSelect;
export type NewPaymentIntent = typeof paymentIntents.$inferInsert;

export type Refund = typeof refunds.$inferSelect;
export type NewRefund = typeof refunds.$inferInsert;

export type StripeEventSeen = typeof stripeEventsSeen.$inferSelect;
export type NewStripeEventSeen = typeof stripeEventsSeen.$inferInsert;

/* -------------------------------------------------------------------------- */
/*  Relations — payments                                                      */
/* -------------------------------------------------------------------------- */

export const paymentIntentsRelations = relations(paymentIntents, ({ one, many }) => ({
  order: one(orders, {
    fields: [paymentIntents.orderId],
    references: [orders.id],
  }),
  refunds: many(refunds),
}));

export const refundsRelations = relations(refunds, ({ one }) => ({
  paymentIntent: one(paymentIntents, {
    fields: [refunds.paymentIntentId],
    references: [paymentIntents.id],
  }),
}));