/**
 * Apply migrations to the configured DATABASE_URL.
 *
 * Two flavors of migration live in db/migrations:
 *   - 0000_bootstrap_extensions.sql, 0002_search_index.sql, 0003_reviews.sql,
 *     …  — hand-authored SQL applied directly with `pool.query(...)`. They use
 *     `IF NOT EXISTS` and `DO $$ … $$` guards so they are safe to re-run.
 *   - Anything generated by `drizzle-kit generate` lands under
 *     db/migrations/generated/ and is applied via Drizzle's migrator.
 *
 * Apply order: hand-authored files in lexical order, then Drizzle-generated
 * migrations on top. New tables introduced in the generated layer reference
 * tables the hand-authored files create (e.g. `reviews` references `listings`),
 * so order matters.
 *
 * Used by docker entrypoint, CI smoke test, and local dev.
 */
import { drizzle } from "drizzle-orm/node-postgres";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import { Pool } from "pg";
import { readdirSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

async function main() {
  const url = process.env.DATABASE_URL;
  if (!url) {
    console.error("DATABASE_URL is not set");
    process.exit(1);
  }
  const pool = new Pool({ connectionString: url });

  // 1. Drizzle-generated migrations (if any have been produced) — applied
  //    FIRST so the core tables (`listings`, `users`, …) exist before the
  //    hand-authored migrations reference them. See db/migrations/0002_search_index.sql
  //    comment for the rationale.
  const migrationsDir = resolve(process.cwd(), "db/migrations");
  const generatedDir = resolve(migrationsDir, "generated");
  try {
    const stat = readdirSync(generatedDir);
    if (stat.length > 0) {
      console.log("Applying drizzle-kit-generated migrations…");
      const db = drizzle(pool);
      await migrate(db, { migrationsFolder: generatedDir });
    }
  } catch (err) {
    // generated/ may not exist yet — that's fine, drizzle-kit creates it.
    if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
  }

  // 2. Hand-authored bootstrap SQL — apply every *.sql that lives directly
  //    under db/migrations (excluding generated/ subdirectory).
  const handFiles = readdirSync(migrationsDir)
    .filter((f) => f.endsWith(".sql"))
    .sort();

  for (const file of handFiles) {
    console.log(`Applying hand-authored migration ${file}…`);
    const sql = readFileSync(resolve(migrationsDir, file), "utf8");
    await pool.query(sql);
  }

  console.log("Migrations complete.");
  await pool.end();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});